// All realtime event types and their payload shapes
export const EVENT_TYPES = {
  TASK_CREATED: 'TASK_CREATED',
  TASK_DELIVERED: 'TASK_DELIVERED',
  TASK_SEEN: 'TASK_SEEN',
  TASK_RESPONDED: 'TASK_RESPONDED',
  TASK_EVALUATING: 'TASK_EVALUATING',
  TASK_EVALUATED: 'TASK_EVALUATED',
  TASK_COMPLETED: 'TASK_COMPLETED',
  TASK_IGNORED: 'TASK_IGNORED',
  TASK_REJECTED: 'TASK_REJECTED',

  AI_MESSAGE_CREATED: 'AI_MESSAGE_CREATED',

  EMPLOYEE_UPDATED: 'EMPLOYEE_UPDATED',
  EMPLOYEE_SCORE_UPDATED: 'EMPLOYEE_SCORE_UPDATED',
  EMPLOYEE_RANK_CHANGED: 'EMPLOYEE_RANK_CHANGED',

  PROMOTION_GRANTED: 'PROMOTION_GRANTED',
  EMERGENCY_TRIGGERED: 'EMERGENCY_TRIGGERED',

  NOTIFICATION_CREATED: 'NOTIFICATION_CREATED',
  SCHEDULED_JOB_CREATED: 'SCHEDULED_JOB_CREATED',
} as const;

export type EventType = (typeof EVENT_TYPES)[keyof typeof EVENT_TYPES];

export interface RealtimeEvent {
  event: EventType;
  timestamp: string;
  data: Record<string, unknown>;
}
