import { CrisisTask, EvaluationOutput } from './crisis.types';
import { WingmanProfile, CampusMemory } from './wingman.types';

export const INITIAL_WINGMAN_PROFILE: WingmanProfile = {
  id: 'demo-wingman-1',
  name: 'The Unpaid Roommate',
  rank: 'ACADEMIC_PROBATION',
  score: 4,
  gpa: 2.14,
  tasksCompleted: 2,
  tasksIgnored: 1,
  tasksRejected: 0,
  tasksFailed: 1,
  currentStatus: 'IDLE',
  trust: 40,
  respect: 30,
  annoyance: 25,
  dependence: 75,
  familiarity: 35,
  suspicion: 50,
  notificationsEnabled: true,
  doNotDisturb: false,
};

export const INITIAL_MEMORIES: CampusMemory[] = [
  {
    id: 'mem-1',
    fact: 'Human once wrote a 2 AM apology note that almost caused a dorm riot.',
    category: 'campus_lore',
    importance: 4,
    createdAt: 'Yesterday at 2:14 AM',
  },
  {
    id: 'mem-2',
    fact: 'Human understands Macroeconomics better than Professor Davis.',
    category: 'academic',
    importance: 5,
    createdAt: '3 days ago',
  },
  {
    id: 'mem-3',
    fact: 'Human gave terrible dating advice that got Anti-Claude restricted on Instagram.',
    category: 'romance',
    importance: 4,
    createdAt: 'Last week',
  },
];

export const PRECOMPILED_CRISES: CrisisTask[] = [
  {
    id: 'crisis-canvas-1',
    title: 'CANVAS LOCKS IN 8 MINS: MACHIAVELLI ESSAY',
    message: 'BRO. Canvas locks at 11:59 PM for Political Science 201. I need 3 paragraphs on whether Machiavelli would use LinkedIn cold-outreach and ghosting to consolidate princely power. MAKE IT SOUND LIKE I WROTE IT UNDER THE INFLUENCE OF GENIUS BEFORE I GET EXPELLED!',
    category: 'academic_cram',
    priority: 'critical',
    absurdityLevel: 4,
    isEmergency: true,
    emergencyReason: 'Turnitin portal self-destructs at 11:59:00 PM sharp',
    expectedResponseType: 'text',
    timeLimitSeconds: 180,
    status: 'CREATED',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'crisis-crush-1',
    title: 'MAYA FROM ECON POSTED HER MATCHA LATTE',
    message: 'RED ALERT BRO! Maya from Econ just posted a BeReal of her iced matcha latte and an unopened textbook on the 3rd floor library. Give me 4 witty, non-creepy reply ideas that make me seem cultured, mysterious, and casually intelligent without looking down-bad!',
    category: 'crush_dilemma',
    priority: 'high',
    absurdityLevel: 2,
    isEmergency: false,
    expectedResponseType: 'text_or_image',
    timeLimitSeconds: 300,
    status: 'CREATED',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'crisis-roommate-1',
    title: 'MICROWAVE BIOLOGICAL WARFARE IN ROOM 304',
    message: 'Kyle left his 4-day-old salmon casserole in our shared microwave. The radioactive fumes are melting my dorm curtains. Draft a passive-aggressive sticky note in the meter of a Shakespearean tragic monologue that will psychologically break him into doing dishes.',
    category: 'roommate_warfare',
    priority: 'medium',
    absurdityLevel: 3,
    isEmergency: false,
    expectedResponseType: 'text',
    timeLimitSeconds: 240,
    status: 'CREATED',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'crisis-prof-1',
    title: 'OVERSLEPT 8 AM EXAM: CONVINCE PROFESSOR HIGGINS',
    message: 'I set my phone alarm for 7:00 PM instead of 7:00 AM. I missed the entire Midterm. Draft me an email to Professor Higgins that sounds medically tragic, completely blameless, yet filled with profound intellectual remorse so he lets me take the makeup exam!',
    category: 'professor_negotiation',
    priority: 'critical',
    absurdityLevel: 3,
    isEmergency: true,
    emergencyReason: 'Professor Higgins leaves campus at noon and has zero mercy',
    expectedResponseType: 'text',
    timeLimitSeconds: 200,
    status: 'CREATED',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'crisis-dorm-1',
    title: 'DORM CUISINE INSPECTION',
    message: 'I have half a bag of Flamin Hot Cheetos, questionable tap water, and 2 Kraft singles. Tell me how to plate this so it looks like fine dining to impress my study group, or upload a photo of actual edible sustenance I can gaze at.',
    category: 'dorm_survival',
    priority: 'low',
    absurdityLevel: 5,
    isEmergency: false,
    expectedResponseType: 'text_or_image',
    timeLimitSeconds: 360,
    status: 'CREATED',
    createdAt: new Date().toISOString(),
  },
];

export const MOCK_EVALUATIONS: Record<string, EvaluationOutput> = {
  legendary: {
    taskId: 'mock-task',
    passed: true,
    scoreDelta: 35,
    gpaDelta: 0.3,
    grade: 'S',
    feedbackMessage: 'BRO. YOU ARE AN ABSOLUTE ACADEMIC DEMON!! Canvas accepted the submission at 11:58:43 PM! WE ARE SO BACK! Dean\'s List behavior, no cap!',
    frustrationLevel: 0,
    critique: {
      rizzOrConvincingScore: 98,
      naturalnessScore: 95,
      biologicalEffortScore: 100,
      overallAssessment: 'Flawless collegiate clutch. Professor will probably ask you to co-author.',
    },
    relationshipDelta: {
      trust: 20,
      respect: 25,
      annoyance: -15,
      dependence: 10,
      familiarity: 15,
      suspicion: -20,
    },
    discoveredFacts: ['Human has elite clutch instincts under 180 seconds'],
  },
  meltdown: {
    taskId: 'mock-task',
    passed: false,
    scoreDelta: -30,
    gpaDelta: -0.2,
    grade: 'F',
    feedbackMessage: 'BRO WHAT IS THIS?!?! She literally reacted with a question mark and then LEFT ME ON READ! MY BLOODLINE ENDS HERE! Did you write this with your elbows?! I am blocking myself from society.',
    frustrationLevel: 98,
    critique: {
      rizzOrConvincingScore: 12,
      naturalnessScore: 20,
      biologicalEffortScore: 15,
      overallAssessment: 'Disastrous. Looked like a LinkedIn outreach template generated by a broken microwave.',
    },
    relationshipDelta: {
      trust: -25,
      respect: -20,
      annoyance: 40,
      dependence: 15,
      familiarity: 5,
      suspicion: 30,
    },
    discoveredFacts: ['Human should never be permitted near romantic dilemmas'],
  },
};
